### PR TITLE
Changed vertx-core scope to provided

### PR DESCRIPTION
**Pull request by eemmiirr**
Change the scope to provided so the project can define it's own vertx version

### CODE REVIEW

**Comment by adrianluisgonzalez** [comment]
Can't you just set the ${vertx.version} property in your project to change the version?

**Comment by eemmiirr** [comment]
I am not including this pom as my parent pom so this wouldn't help. When i get the vertx-jersey jar for instance it will contain the vertx-core jar inside. I have then to exclude it in maven.

**Comment by adrianluisgonzalez** [comment]
What about using <dependencyManagement> then?

**Comment by eemmiirr** [comment]
vertx-core should be provided like servlets are when you develop a web app. It not part of the library it's the platform it should run on

**Comment by adrianluisgonzalez** [comment]
This is consistent with the vertx-3 extension projects, for example:
* https://github.com/vert-x3/vertx-web/blob/master/pom.xml#L38
* https://github.com/vert-x3/vertx-rabbitmq-client/blob/master/pom.xml#L37
* https://github.com/vert-x3/vertx-embedded-mongo-db/blob/master/pom.xml#L53

vertx-jersey uses features specific to the version of vertx it was compiled with, if you really want to change the version then <dependencyManagement> will achieve that.

Your change is breaking, so I would hesitate, plus there is a clear work around for what you're trying to achieve no?

**Comment by eemmiirr** [comment]
Thanks for the info i didn't know that this is the desired way to do it with vertx since usually minor versions should not be breaking. Thanks for your help will close the PR

**Pull request closed without merging**
